<?php
// Load Dolibarr environment
$res = 0;
// Try main.inc.php into web root known defined into CONTEXT_DOCUMENT_ROOT (not always defined)
if (!$res && !empty($_SERVER["CONTEXT_DOCUMENT_ROOT"])) $res = @include $_SERVER["CONTEXT_DOCUMENT_ROOT"]."/main.inc.php";
// Try main.inc.php into web root detected using web root calculated from SCRIPT_FILENAME
$tmp = empty($_SERVER['SCRIPT_FILENAME']) ? '' : $_SERVER['SCRIPT_FILENAME']; $tmp2 = realpath(__FILE__); $i = strlen($tmp) - 1; $j = strlen($tmp2) - 1;
while ($i > 0 && $j > 0 && isset($tmp[$i]) && isset($tmp2[$j]) && $tmp[$i] == $tmp2[$j]) { $i--; $j--; }
if (!$res && $i > 0 && file_exists(substr($tmp, 0, ($i + 1))."/main.inc.php")) $res = @include substr($tmp, 0, ($i + 1))."/main.inc.php";
if (!$res && $i > 0 && file_exists(dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php")) $res = @include dirname(substr($tmp, 0, ($i + 1)))."/main.inc.php";
// Try main.inc.php using relative path
if (!$res && file_exists("../main.inc.php")) $res = @include "../main.inc.php";
if (!$res && file_exists("../../main.inc.php")) $res = @include "../../main.inc.php";
if (!$res && file_exists("../../../main.inc.php")) $res = @include "../../../main.inc.php";
if (!$res) die("Include of main fails");

require_once DOL_DOCUMENT_ROOT.'/core/class/html.formcompany.class.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/date.lib.php';
require_once DOL_DOCUMENT_ROOT.'/core/lib/company.lib.php';

// load facturadian libraries
require_once __DIR__.'/class/cronjobs.class.php';

// for other modules
//dol_include_once('/othermodule/class/otherobject.class.php');

// Load translation files required by the page
$langs->loadLangs(array("facturadian@facturadian", "other"));

$action     = GETPOST('action', 'aZ09') ?GETPOST('action', 'aZ09') : 'view'; // The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = GETPOST('massaction', 'alpha'); // The bulk action (combo box choice into lists)
$show_files = GETPOST('show_files', 'int'); // Show files area generated by bulk actions ?
$confirm    = GETPOST('confirm', 'alpha'); // Result of a confirmation
$cancel     = GETPOST('cancel', 'alpha'); // We click on a Cancel button
$toselect   = GETPOST('toselect', 'array'); // Array of ids of elements selected into a list
$contextpage = GETPOST('contextpage', 'aZ') ? GETPOST('contextpage', 'aZ') : 'cronjobslist'; // To manage different context of search
$backtopage = GETPOST('backtopage', 'alpha'); // Go back to a dedicated page
$optioncss  = GETPOST('optioncss', 'aZ'); // Option for the css output (always '' except when 'print')

$id = GETPOST('id', 'int');


// Output page
// --------------------------------------------------------------------

llxHeader('', $title, $help_url);
print load_fiche_titre($langs->trans("Programar envio de documentos a la DIAN", $langs->transnoentitiesnoconv("FacturaDian")));


	// ESTE CODIGO ES LA GRILLA
	print "<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
	<link type='text/css' href='java/css/redmond/jquery-ui-1.8.2.custom.css' rel='stylesheet' />
	<link rel='stylesheet' href='java/css/ui.jqgrid.css' type='text/css' media='screen'  />
	<link rel='stylesheet' href='java/css/ui.multiselect.css' type='text/css' media='screen'/>
	<link rel='stylesheet' href='java/css/thickbox.css' type='text/css' media='screen' />
	<script src='java/js/jquery.js' type='text/javascript'></script>
	<script src='java/js/jquery-ui-1.8.2.custom.min.js' type='text/javascript'></script>
	<script src='java/js/i18n/grid.locale-sp.js' type='text/javascript'></script>
	<script src='java/js/jquery.jqGrid.min.js' type='text/javascript'></script>
	<script src='java/js/ui.multiselect.js' type='text/javascript'></script>
	<script src='java/js/thickbox-compressed.js' type='text/javascript'></script>
	<script src='java/js/jquery.ui.datepicker-es.js' type='text/javascript'></script>";
	print "<script type='text/javascript'>

	function funcion_eliminar(cron)
	{
		$.post('./cronjobs_card.php?action=eliminar',{cron:cron}, function () {
			$('#list').trigger('reloadGrid');
		});
	}
	function funcion_lanzar(cron)
	{
		$.post('./cronjobs_card.php?action=lanzar',{cron:cron}, function () {
			$('#list').trigger('reloadGrid');
		});
	}
	jQuery(document).ready(function(){
		jQuery('#list').jqGrid({
			url:'./cronjobs_card.php?action=grilla', 
			datatype: 'xml',
			mtype: 'POST',
			colNames:['Acciones','Documento','Prefijo','Dia de la semana Ej 1=Lunes','Hora','Minuto','Ambiente','cantidad','rowid'],
			colModel :[
				{name:'acciones', index:'acciones', width:140 },
				{name:'documento', index:'documento', width:100, sortable:true, editable:true, edittype:'select', editoptions:{value:{'fa':'factura','nc':'credito','nd':'debito'}} },
				{name:'prefijo', index:'prefijo', width:200, sortable:true, editable:true  },
				{name:'dias', index:'dias', width:250, sortable:true, editable:true  },
				{name:'hora', index:'hora', width:100, sortable:true, editable:true  },
				{name:'minuto', index:'minuto', width:100, sortable:true, editable:true },      
				{name:'ambiente', index:'ambiente', width:100, sortable:true, editable:true, edittype:'select', editoptions:{value:{'habilitacion':'habilitacion','produccion':'produccion'}} },
				{name:'cantidad', index:'cantidad', width:180, sortable:true, editable:true  },
				{name:'rowid', index:'rowid', width:100, sortable:true, editable:false  }
				],
			editurl: './cronjobs_card.php?action=editar',
			multiselect: false,
			pager: jQuery('#pager'),
			rowNum:100,
			rowList:[100],
			sortname: 'idcron',
			sortorder: 'documento',
			loadComplete: function(){
				var ids = jQuery('#list').getDataIDs();
				for(var i=0;i<ids.length;i++){
					var cl = ids[i];
					ca = '<A HREF=\'javascript:funcion_eliminar('+cl+');\'>Eliminar</A>&nbsp;&nbsp;&nbsp;';
					ce = '<A HREF=\'javascript:funcion_lanzar('+cl+');\'>Lanzar</A>&nbsp;&nbsp;&nbsp;';
					jQuery('#list').setRowData(ids[i],{acciones:ca+ce})	
				}
			},
			viewrecords: true,
			theme: 'green',
			caption: '<font color=white>Programacion de envio de documentos diaria a la Dian y al cliente</font> ', 
			height:'auto',
			subGrid : true,
			subGridUrl: './cronjobs_card.php?action=subgrid',
			subGridModel: [{ name  : ['Tarea','Prefijo','Detalle','Accion'],
						     width : [100,100,300,100]} 
			],
			ondblClickRow: function(){
				var row_id = $('#list').getGridParam('selrow'); jQuery('#list').editRow(row_id, true);
			}
		});
		//Barra de navegación
		jQuery('#list').navGrid('#pager',{
			edit:true, 
			add:true, 
			del:true, 
			search:false,
			view:false
		});
		// Editar Propiedades de la ventana de Adición/Edición
		jQuery.jgrid.edit = {
			top: 200,
			left: 140,
			height:300,
			width: 500,
			addCaption: 'Adicionar',
			editCaption: 'Editar',
			bSubmit: 'Guardar',
			bCancel: 'Cancelar',
			modal:true,
			processData: 'Procesando...',
			closeAfterAdd:true,
			closeAfterEdit:true,
			reloadAfterSubmit:true
		};
	});	
	</script>";
	
	print "<table id='list'></table>
			<div id='pager'></div>";
	//FIN GRILLA



// End of page
llxFooter();
$db->close();
